### ISSUE TITLE
Allow users to update friend request list on registration form before team formation

### ISSUE THREAD

**Issue by tnan123** [cyanfish/heltour#263]
Currently players have to contact mods and mods have to manually update the registration. It would be nice if users could update their own friends list after registration submission but before team formation.

**Comment by lakinwecker** [comment]
I agree. I think we should require "sign in" to the website in order to register. Once you register, you should be taken to a dashboard page, where you can update your registration. This should also serve as a place where you can confirm your registration status.

Finally, it can also be a place where we include any onboarding information that we want to convey to them.  It should also be obvious that they can return to this page to see their current pairings, current league status and update their availability.

**Comment by cyanfish** [comment]
Fixed in #280.
